version: "3.9"
services:
  worker:
    build: .
    environment:
      STRING_SESSION: $STRING_SESSION
      APP_ID: $APP_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      TG_BOT_TOKEN: $TZ_BOT_TOKEN # Not mandatory
      TZ: $TZ # Not mandatory
      DATABASE_URL: $DATABASE_URL  # defaults to None
      OKTETO_TOKEN: $OKTETO_TOKEN
